spring.application.name=flix

#URl de conexão
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Usuario e senha
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Driver
spring.datasource.url=${DB_URL}

#Dialeto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#Mostra o SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true